### ISSUE TITLE
sharing ownership, moving or forking

### ISSUE THREAD

**Issue by aperrot42** [mcluseau/sync2kafka#3]
Hi @mcluseau for isi devs to co-work on sync2kafka, would you either :  
 - allow someone working at isi (we to share ownership of sync2kafka (and related dependencies).
 - move sync3kafka and dependencies to an "isi.nc" group in github
 - prefer that isi forks the repo and maintain a forked version ?

**Comment by mcluseau** [comment]
I think it's better if you fork and send PRs, this is a small piece of software here so it should stabilize quickly and reviewing code is a good practice ;-)
